import type { SpotifyTrack } from "@/types";

const TITLE_TEMPLATES = [
  "{mood} Sessions",
  "The {mood} Hour",
  "{mood} Atmosphere",
  "Midnight {mood}",
  "{mood} Frequencies",
  "After Dark: {mood}",
  "{mood} Landscapes",
  "{mood} Drift",
  "Sonic {mood}",
  "{mood} Echoes",
];

const DESCRIPTION_TEMPLATES = [
  "A curated collection of {trackCount} tracks exploring {moods}. Generated by Sonic Atmosphere.",
  "Immerse yourself in {moods} with this handpicked selection of {trackCount} tracks.",
  "{trackCount} tracks of pure {moods}. Curated by vibe, not by algorithm.",
  "Drift through {moods} — {trackCount} tracks selected for the perfect atmosphere.",
];

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function pickRandom<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function extractMoodWords(prompt: string): string[] {
  const keywords = [
    "dreamy", "acoustic", "melancholy", "melancholic", "shoegaze",
    "electronic", "ambient", "nocturnal", "lo-fi", "cinematic",
    "energetic", "indie", "folk", "jazz", "chill", "dark",
    "ethereal", "atmospheric", "soft", "gentle", "intense",
    "moody", "warm", "cold", "neon", "synthwave", "retrowave",
  ];
  const lower = prompt.toLowerCase();
  return keywords.filter((k) => lower.includes(k));
}

function extractArtistGenres(tracks: SpotifyTrack[]): string[] {
  // Use artist names to hint at genre when we don't have genre data on tracks
  return [];
}

export function generatePlaylistTitle(
  prompt: string,
  tracks: SpotifyTrack[]
): string {
  const moods = extractMoodWords(prompt);

  if (moods.length > 0) {
    const mood = capitalize(pickRandom(moods));
    return pickRandom(TITLE_TEMPLATES).replace("{mood}", mood);
  }

  // Fallback: use first few words of prompt
  const words = prompt.split(/\s+/).slice(0, 3);
  if (words.length > 0) {
    return capitalize(words.join(" ")) + " Mix";
  }

  return "Sonic Atmosphere Mix";
}

export function generatePlaylistDescription(
  prompt: string,
  tracks: SpotifyTrack[]
): string {
  const moods = extractMoodWords(prompt);
  const moodString = moods.length > 0
    ? moods.map(capitalize).join(", ")
    : prompt.slice(0, 50);

  return pickRandom(DESCRIPTION_TEMPLATES)
    .replace("{moods}", moodString)
    .replace("{trackCount}", String(tracks.length));
}
